#!/bin/bash
. base
login=$1
senha=$2
uf=$3

checkLogin

[ $needjoin -eq 1 ] && sudo net ads join -U$login%$senha -W INTRANET &> /dev/null


shift 3

ativar=$*

for i in $ativar
do
	php5 ativar.php $login $senha $uf $i
	/var/www/sis/ad/senhas $login $senha $i 2> /dev/null
	echo $i >> upload/ativacao-$login-$data
done
