#!/bin/bash
. base
login=$1
senha=$2
uf=$3



shift 3

ativar=$*

for i in $ativar
do
	php5 ativar.php $login $senha $uf $i
	/var/www/sis/ad/senhas $login $senha $i 2> /dev/null
	echo $i >> upload/ativacao-$login-$data
done
