#!/bin/bash
. base
login=$1
senha=$2
shift 2
lista=$@

[ $needjoin -eq 1 ] && sudo net ads join -U$login%$senha -W INTRANET &> /dev/null

echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"

php5 buscar.php $login $senha $lista
