#!/bin/bash
login=$1
senha=$2
shift 2
lista=$@

[[ $(sudo net ads testjoin) ]] || sudo net ads join -U$login%$senha -W INTRANET 2> /dev/null

echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"

php5 buscar.php $login $senha $lista
