#!/bin/bash
dos2unix $3
sed -i '1d' $3
loginadm=$1
passadm=$2

[[ $(sudo net ads testjoin) ]] || sudo net ads join -U$loginadm%$senhaadm -W INTRANET

cat $3 | xargs -P5 -L1 ./criador2 $loginadm $passadm

data=$(date --rfc-3339=seconds | cut -f1-3 -d- | sed 's/ /-/g' | sed 's/:/-/g')
#mv $3 upload/criacao-$loginadm-$data
