#!/bin/bash
. base

dos2unix $3
ano=$(date +"%Y")
sed -i '1d' $3
login=$1
senha=$2

checkLogin

[ $needjoin -eq 1 ] && sudo net ads join -U$login%$senha -W INTRANET &> /dev/null

while read line
do
        user=$(echo $line | cut -f1 -d,)
        first=$(echo $line | cut -f2 -d,)
        last=$(echo $line | cut -f3 -d,)
        UF=$(echo $line | cut -f4 -d,)
	group=${line/*,/}
        php5 criar.php $user "${first~}" "${last~}" ${UF^^} $login $senha $ano
	[ ${#group} -gt 0 ] && {
	        echo "<ul>"
	        for group in ${line/*,/}
        	do
                	echo "<li><p style='color:#D36F17;margin:0px;'>Usuário <b>${line/,*/}</b> adicionado ao grupo <b>$group</b>.</p></li>"
	                net rpc group addmem $group ${line/,*/} -S 10.100.10.3 -U$login%$senha
        	done
	        echo "</ul>"
	}
done < $3

mv $3 upload/criacao-$login-$data
