#!/bin/bash
. base

while getopts "L:S:G:U:" option
do
	case "$option" in
	L)	login="$OPTARG";;
	S)	senha="$OPTARG";;
	G)	GRPS="$OPTARG";;
	U)	USRS="$OPTARG";;
	esac
done

[[ $(sudo net ads testjoin) ]] || sudo net ads join -U$login%$senha -W INTRANET



for group in $GRPS
do
	for user in $USRS
	do
		net rpc group addmem $group $user -S 10.100.10.3 -U$login%$senha &> .tmp$$
		[ $? -eq 0 ] && {
			printOK "Usuário <b>$user</b> adicionado ao grupo <b>$group</b>";
			echo $user-$group >> upload/grupos-$login-$data;
			} || {
				[[ $(cat .tmp$$ | grep MEMBER_IN_GROUP) ]] && printWarning "Usuário <b>$user</b> já está no grupo <b>$group</b>";
				[[ $(cat .tmp$$ | grep "Could not lookup group name") ]] && printError "Grupo <b>$group</b> inexistente";
				[[ $(cat .tmp$$ | grep NT_STATUS_NONE_MAPPED) ]] && printError "Usuário <b>$user</b> inexistente";
			}
		rm .tmp$$
	done
done

