#!/bin/bash
. base
data=$(date --rfc-3339=seconds | cut -f1-3 -d- | sed 's/ /-/g' | sed 's/:/-/g')

while getopts "L:S:G:U:" option
do
	case "$option" in
	L)	login="$OPTARG";;
	S)	senha="$OPTARG";;
	G)	GRPS="$OPTARG";;
	U)	USRS="$OPTARG";;
	esac
done

[[ $(sudo net ads testjoin) ]] || sudo net ads join -U$login%$senha -W INTRANET



for group in $GRPS
do
	for user in $USRS
	do
		net rpc group addmem $group $user -S 10.100.10.3 -U$login%$senha &> .tmp$$
		[ $? -eq 0 ] && {
			printOK "Usuário <b>$user</b> adicionado ao grupo <b>$group</b>";
			echo $user-$group >> upload/grupos-$login-$data;
			} || printError "$(cat .tmp$$)";
		rm .tmp$$
	done
done

