#!/bin/bash
. base
login=$1
senha=$2

shift 2

reset=$*
ano=$(date +"%Y")

for i in $reset
do
	echo "<p style='color:#2CA823;'>"
	sudo net ads password $i@INTRANET Nova$ano -U$login@INTRANET%$senha &> .tmp$$
	[[ $(grep Preauthentication .tmp$$) ]] && printError "Falha de autenticacao";
	[[ $(grep Generic .tmp$$) ]] && printError "Usuario $i nao encontrado";
	[[ $(grep "@INTRANET completed" .tmp$$) ]] && printOK "Senha para $i alterada para Nova$ano.";
	rm .tmp$$
	echo "</p>"
	php5 reset.php $login $senha $i $ano
	echo $i >> upload/reset-$login-$data
done
